[workspace]
pr_draft = false
changelog_config = "cliff.toml"
pr_labels = ["release"]
git_release_name = "v{{ version }}"
commit_message = "chore(release): {{ crate_name }} v{{ version }} [skip ci]"

changelog_update = true

[[package]]
name = "executor-core"

[[package.files_to_update]]
path = "README.md"
search = 'executor-core = "[0-9]+\.[0-9]+(\.[0-9]+)?"'
replace = 'executor-core = "{{ version }}"'
