[workspace]
pr_draft = false
changelog_config = "cliff.toml"
pr_labels = ["release"]
git_release_name = "v{{ version }}"
publish = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "executor-core"
